# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPRD) += ums512-1h10.dtb

dtbo-$(CONFIG_ARCH_SPRD) += ums512-1h10-overlay.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
